### ISSUE TITLE
Issue with emoticons

### ISSUE THREAD

**Issue by GregMage** [GregMage/tinymce5#1]
Problem when adding an emoticon, xoops does not accept the emoticon code in the database:

`news_news= <p>c\'est la news " attention" 2</p>\r\n<p>😀</p>`
`Error number: 1366
Error message: Incorrect string value: '\xF0\x9F\x98\x80`

**Comment by geekwright** [comment]
This sounds like a mysql utf8mb3 vs utfmb4  character set issue. The emoji range requires utf8mb4 . That would be required on the connection and the table column definition.

**Comment by GregMage** [comment]
Thank you for this information. I delete the emoticons that are integrated. It is too complex for users to change this.
